### ISSUE TITLE
Was ist der Zweck dieses Repos?

### ISSUE THREAD

**Issue by konstin** [codeformunich/codeformunich.github.io#1]

**Comment by mattfullerton** [comment]
Die Idee war sicher eine kostenlose Internetseite aufzustellen. Dafür fehlt das gh-pages Branch, meine ich.

**Comment by konstin** [comment]
Nein, man kann dafür jeden Branch nutzen: https://github.com/codeformunich/codeformunich.github.io/settings.

Auf der Seite https://codeformunich.github.io findet sich aber im Momentlediglich eine Vorlage von GitHub.

**Comment by saerdnaer** [comment]
Die ursprüngliche Idee war eine Link Liste zu den einzelnen Apps, also z.b. https://codeformunich.github.io/FinderApp/

Insbesondere für die verschiedenen Forks der FinderApp und wenn man grade nicht weiß wie die Groß-/Kleinschreibung da ausfällt ;-).

Siehe auch https://github.com/codeformunich/FinderApp/issues/32#issuecomment-74905027

**Comment by konstin** [comment]
An sich finde ich die Idee einer Link-Liste gut, aber macht das nicht schon http://codefor.de/muenchen/index.html?

**Comment by saerdnaer** [comment]
Nein, http://codefor.de/muenchen/ erfüllt den geplanten Zweck nicht.
